package com.nyilg.game.statemachine;

public enum GameState {
	START, DEVELOPER_LOGO, START_SCREEN, GAME_SETUP, INTRO_VIDEO, LEVEL_LOADING, HIGHSCORE, LEVEL_PLAYING, INGAME_VIDEO, INGAME_SETUP, END_VIDEO, CREDITS
}
